export enum OrderStatus {
  INIT = "INIT",
  CONFIRMED = "CONFIRMED",
  PREPARING = "PREPARING",
  READY_FOR_PICKUP = "READY_FOR_PICKUP",
  READY_FOR_DISPATCH = "READY_FOR_DISPATCH",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  PICKED_UP = "PICKED_UP",
  CANCELLED_BY_CLIENT = "CANCELLED_BY_CLIENT",
  CANCELLED_BY_COOK = "CANCELLED_BY_COOK",
  CANCELLED_BY_ADMIN = "CANCELLED_BY_ADMIN",
  REFUNDED = "REFUNDED",
}

export type TerminalOrderStatus =
  | OrderStatus.DELIVERED
  | OrderStatus.PICKED_UP
  | OrderStatus.CANCELLED_BY_CLIENT
  | OrderStatus.CANCELLED_BY_COOK
  | OrderStatus.CANCELLED_BY_ADMIN
  | OrderStatus.REFUNDED;

